[build]
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/neon"]

[functions."obras"]
  included_files = ["netlify/functions/_db.js"]

[functions."items"]
  included_files = ["netlify/functions/_db.js"]
